import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_TITLE,
} from '@/constants/navigation.constant'

import {
    ADMIN,
    AGENT,
    AGENCY_SUPERVISOR,
    SUPERVISOR,
    AGENT_CABINET_ROLES,
    CONTENT_MANAGER_ALLOWED_ROLES,
} from '@/constants/roles.constant'
import { USER_BONUS } from '@/constants/bonuses.constant'

import type { NavigationTree } from '@/@types/navigation'

const agentCabinetAuthority = [...AGENT_CABINET_ROLES]
const contentManagerAllowedAuthority = [...CONTENT_MANAGER_ALLOWED_ROLES]
const objectsAuthority = [ADMIN, AGENT, AGENCY_SUPERVISOR, SUPERVISOR]
const supervisorOnlyAuthority = [SUPERVISOR]
const managementAuthority = [SUPERVISOR, AGENCY_SUPERVISOR, ADMIN]

const navigationConfig: NavigationTree[] = [
    {
        key: 'main',
        path: '',
        title: 'Основное',
        translateKey: 'nav.main.main',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: contentManagerAllowedAuthority,
        subMenu: [
            {
                key: 'home',
                path: '/home',
                title: 'Дашборд',
                translateKey: 'nav.home',
                icon: 'home',
                type: NAV_ITEM_TYPE_ITEM,
                authority: agentCabinetAuthority,
                subMenu: [],
            },
            {
                key: 'fixations',
                path: '/fixations',
                title: 'Фиксации',
                translateKey: 'nav.fixations',
                icon: 'fixations',
                type: NAV_ITEM_TYPE_ITEM,
                authority: agentCabinetAuthority,
                subMenu: [],
            },
            {
                key: 'objects',
                path: '/objects',
                title: 'Объекты',
                translateKey: 'nav.objects',
                icon: 'objects',
                type: NAV_ITEM_TYPE_ITEM,
                authority: objectsAuthority,
                subMenu: [],
            },
            {
                key: 'commercialPremises',
                path: '/commercial-premises',
                title: 'Коммерческие помещения',
                translateKey: 'nav.commercialPremises',
                icon: 'objects',
                type: NAV_ITEM_TYPE_ITEM,
                authority: objectsAuthority,
                subMenu: [],
            },
        ],
    },
    {
        key: 'tools',
        path: '',
        title: 'Инструменты',
        translateKey: 'nav.tools.tools',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: objectsAuthority,
        subMenu: [
            {
                key: 'favoritePremises',
                path: '/favorite-premises',
                title: 'Избранное',
                translateKey: 'nav.favoritePremises',
                icon: 'favoritePremises',
                type: NAV_ITEM_TYPE_ITEM,
                authority: objectsAuthority,
                subMenu: [],
            },
            {
                key: 'comparisonPremises',
                path: '/comparison-premises',
                title: 'Сравнение',
                translateKey: 'nav.comparisonPremises',
                icon: 'comparisonPremises',
                type: NAV_ITEM_TYPE_ITEM,
                authority: objectsAuthority,
                subMenu: [],
            },
            {
                key: 'mortgageCalculator',
                path: '/mortgage-calculator',
                title: 'Калькулятор',
                translateKey: 'nav.mortgageCalculator',
                icon: 'calculator',
                type: NAV_ITEM_TYPE_ITEM,
                authority: agentCabinetAuthority,
                bonuses: [USER_BONUS.CALCULATOR],
                subMenu: [],
            },
        ],
    },
    {
        key: 'management',
        path: '',
        title: 'Управление',
        translateKey: 'nav.management.management',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: managementAuthority,
        subMenu: [
            {
                key: 'supervisorFixations',
                path: '/supervisor/fixations',
                title: 'Модерация фиксаций',
                translateKey: 'nav.supervisorFixations',
                icon: 'supervisor',
                type: NAV_ITEM_TYPE_ITEM,
                authority: supervisorOnlyAuthority,
                subMenu: [],
            },
            {
                key: 'supervisorAgencies',
                path: '/supervisor/agencies',
                title: 'Агентства',
                translateKey: 'nav.supervisorAgencies',
                icon: 'agencies',
                type: NAV_ITEM_TYPE_ITEM,
                authority: supervisorOnlyAuthority,
                subMenu: [],
            },
            {
                key: 'supervisorUsers',
                path: '/supervisor/users',
                title: 'Пользователи',
                translateKey: 'nav.supervisorUsers',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: managementAuthority,
                subMenu: [],
            },
            {
                key: 'agencyRequests',
                path: '/agency/requests',
                title: 'Заявки в агентство',
                translateKey: 'nav.agencyRequests',
                icon: 'agencyRequests',
                type: NAV_ITEM_TYPE_ITEM,
                authority: managementAuthority,
                subMenu: [],
            },
            {
                key: 'agencyInvitations',
                path: '/agency/invitations',
                title: 'Приглашения',
                translateKey: 'nav.agencyInvitations',
                icon: 'agencyInvitations',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [AGENCY_SUPERVISOR],
                subMenu: [],
            },
        ],
    },
    {
        key: 'content',
        path: '',
        title: 'Информация',
        translateKey: 'nav.content.content',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: contentManagerAllowedAuthority,
        subMenu: [
            {
                key: 'help',
                path: '/help',
                title: 'Помощь',
                translateKey: 'nav.content.help',
                icon: 'help',
                type: NAV_ITEM_TYPE_ITEM,
                authority: contentManagerAllowedAuthority,
                subMenu: [],
            },
            {
                key: 'agentCommission',
                path: '/help/23-agentskoe-voznagrazhdenie',
                title: 'Агентское вознаграждение',
                translateKey: 'nav.content.agentCommission',
                icon: 'agentCommission',
                type: NAV_ITEM_TYPE_ITEM,
                authority: agentCabinetAuthority,
                subMenu: [],
            },
            {
                key: 'offers',
                path: '/offers',
                title: 'Акции',
                translateKey: 'nav.content.offers',
                icon: 'offers',
                type: NAV_ITEM_TYPE_ITEM,
                authority: agentCabinetAuthority,
                bonuses: [USER_BONUS.SPECIAL_OFFERS],
                subMenu: [],
            },
            {
                key: 'profile',
                path: '/account/profile',
                title: 'Профиль',
                translateKey: 'nav.profile',
                icon: 'profile',
                type: NAV_ITEM_TYPE_ITEM,
                authority: contentManagerAllowedAuthority,
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
