import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_TITLE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'main',
        path: '',
        title: 'Основное',
        translateKey: 'nav.main.main',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'home',
                path: '/home',
                title: 'Дашборд',
                translateKey: 'nav.home',
                icon: 'home',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'fixations',
                path: '/fixations',
                title: 'Фиксации',
                translateKey: 'nav.fixations',
                icon: 'fixations',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'objects',
                path: '/objects',
                title: 'Объекты',
                translateKey: 'nav.objects',
                icon: 'objects',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'favoritePremises',
                path: '/favorite-premises',
                title: 'Избранное',
                translateKey: 'nav.favoritePremises',
                icon: 'favoritePremises',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'tools',
                path: '/tools',
                title: 'Инструменты',
                translateKey: 'nav.tools',
                icon: 'tools',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'profile',
                path: '/account/profile',
                title: 'Профиль',
                translateKey: 'nav.profile',
                icon: 'profile',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
    {
        key: 'content',
        path: '',
        title: 'Информация',
        translateKey: 'nav.content.content',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [],
        subMenu: [
            {
                key: 'news',
                path: '/news',
                title: 'Новости',
                translateKey: 'nav.content.news',
                icon: 'news',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'events',
                path: '/events',
                title: 'События',
                translateKey: 'nav.content.events',
                icon: 'events',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'help',
                path: '/help',
                title: 'Помощь',
                translateKey: 'nav.content.help',
                icon: 'help',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
