FROM node:22-alpine as build

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json to the container
# COPY package*.json ./

# Install dependencies
# RUN npm ci

# Copy the rest of the application code to the container
# COPY . .

# Build the React app
# RUN npm run build
CMD ["sh", "-c", "tail -f /dev/null"]
